# .readthedocs.yml

version: 2

# Configuration de Python
python:
  version: 3.8
  install:
    - requirements: docs/requirements.txt  # Assurez-vous que ce fichier existe.

# Sphinx configuration
sphinx:
  configuration: docs/conf.py  # Chemin vers le fichier conf.py
